# Generated by Django 3.2.10 on 2025-04-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_contactsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeasingParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leasing_type', models.CharField(choices=[('rental', 'Rental'), ('consumer', 'Consumer Leasing'), ('cash', 'Cash Loan')], max_length=20)),
                ('package_type', models.CharField(choices=[('basic', 'Basic'), ('comfort', 'Comfort')], max_length=20)),
                ('base_rate_multiplier', models.DecimalField(decimal_places=3, default=1.0, max_digits=5)),
                ('annual_mileage_factor', models.DecimalField(decimal_places=3, default=0.02, max_digits=5)),
                ('contract_length_factor', models.DecimalField(decimal_places=3, default=0.015, max_digits=5)),
                ('initial_payment_discount', models.DecimalField(decimal_places=3, default=0.01, max_digits=5)),
                ('package_base_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leasing Parameter',
                'verbose_name_plural': 'Leasing Parameters',
                'unique_together': {('leasing_type', 'package_type')},
            },
        ),
    ]
