# Generated by Django 5.2 on 2025-04-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20250411_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
    ]
